" install plug if not installed
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

" Bundles
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'crusoexia/vim-monokai'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'mhinz/vim-grepper'
Plug 'roxma/nvim-yarp' " required for deoplete
Plug 'roxma/vim-hug-neovim-rpc' " required for deoplete
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'ervandew/supertab'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/nerdcommenter'
Plug 'tpope/vim-surround'
Plug 'matze/vim-move' " Move blocks of code with ALT+j/k
Plug 'w0rp/ale' " replacement scrooloose/syntastic
Plug 'vim-ruby/vim-ruby'
Plug 'tpope/vim-endwise' " Add 'end' to ruby blocks
Plug 'hashivim/vim-terraform'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rhubarb'
Plug 'gregsexton/gitv', {'on': ['Gitv']}
Plug 'christoomey/vim-tmux-navigator'
Plug 'fatih/vim-go'
Plug 'jceb/vim-orgmode'
Plug 'tpope/vim-speeddating'
Plug 'thoughtbot/vim-rspec'

call plug#end()

" Config
" ======
set t_Co=256
set encoding=utf-8
set number
set hidden
set history=100
set nocompatible
set omnifunc=syntaxcomplete#Complete
set ignorecase
set incsearch
set laststatus=2
set backspace=indent,eol,start

try
  set enc=utf-8
  set fileencoding=utf-8
catch
endtry

" clipboard
if system('uname') == 'Linux'
  set clipboard=unnamedplus
else
  set clipboard=unnamed
endif

" theme
try
  syntax on
  colorscheme monokai
  set background=dark
  let g:airline_powerline_fonts = 1
  set laststatus=2
  let g:airline_theme='powerlineish'
catch
endtry

" Map leader
let mapleader=' '

" Spell
set spelllang=en_gb
set complete+=kspell
nmap <leader>sc :set spell<CR>
nmap <leader>ns :set nospell<CR>

let g:Powerline_symbols = 'fancy'

" Quickly edit/reload the vimrc file

nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

" Map keys
imap jk <ESC>

" Arrows are unvimlike
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>

" splits
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
set splitbelow
set splitright

" File type
autocmd BufRead,BufNewFile {*.markdown,*.mdown,*.mkdn,*.md,*.mkd,*.mdwn,*.mdtxt,*.mdtext,*.text} set filetype=markdown
autocmd BufRead,BufNewFile {Brewfile} set filetype=ruby

" indention
filetype plugin indent on
set nowrap
set tabstop=2
set shiftwidth=2
set softtabstop=2
set smartindent
set autoindent
set expandtab
autocmd Filetype python setlocal ts=4 sw=4 sts=0 expandtab

inoremap <expr><TAB> pumvisible() ? "\<C-n>" : "\<TAB>"

" make supertab close the tern preview
let g:SuperTabClosePreviewOnPopupClose = 1
" make supertab move down instead of up
let g:SuperTabDefaultCompletionType = "<c-n>"

" autoremove white spaces on save
autocmd BufWritePre * :%s/\s\+$//e

" highlight
set hlsearch
set showmatch
nnoremap <silent> <leader>nh :nohl<CR>

" Change cursor shape between insert and normal mode in iTerm2.app
if $TERM_PROGRAM =~ "iTerm"
    let &t_SI = "\<Esc>]50;CursorShape=1\x7" " Vertical bar in insert mode
    let &t_EI = "\<Esc>]50;CursorShape=0\x7" " Block in normal mode
endif

" Tabs with Buffers
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ':t'
" To open a new empty buffer
nmap <leader>T :enew<cr>
" Move to the next buffer
nmap <leader>l :bnext<CR>
" Move to the previous buffer
nmap <leader>h :bprevious<CR>
" Close the current buffer and move to the previous one
nmap <leader>q :bp <BAR> bd #<CR>
" Show all open buffers and their status
nmap <leader>bl :ls<CR>

" deoplete.nvim
let g:deoplete#enable_at_startup = 1
" Ale
let g:ale_fixers = {
\   'ruby': ['rubocop'],
\}
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_sign_column_always = 1

" NerdTree
map <C-n> :NERDTreeToggle<CR>
" autocmd FileType nerdtree nmap <buffer> <CR> go

" fzf
map <C-p> :Files<CR>

" Grepper
map <C-g> :Grepper -tool ag<CR>
nmap gs <plug>(GrepperOperator)
xmap gs <plug>(GrepperOperator)

" Golang
let g:go_disable_autoinstall = 0
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1

" Terraform
let g:terraform_fmt_on_save = 1

" Rspec
let g:rspec_command = '!run-rspec {spec}'
map <Leader>sf :call RunCurrentSpecFile()<CR>
map <Leader>sn :call RunNearestSpec()<CR>
map <Leader>sl :call RunLastSpec()<CR>
map <Leader>sa :call RunAllSpecs()<CR>
