" install plug if not installed
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

" Bundles
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'crusoexia/vim-monokai'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'wincent/vim-clipper'
Plug 'mhinz/vim-grepper'

" Install pynvim if not installed
" Is a requirement of roxma/vim-hug-neovim-rpc
python3 << endpy
try:
    import neovim
except ImportError:
    import subprocess
    import os

    env = dict(os.environ)
    path = env['PATH']
    env['PATH'] = '/opt/homebrew/opt/python@3.11/bin:{}'.format(path)
    # https://github.com/roxma/vim-hug-neovim-rpc/issues/47
    subprocess.call(
        ['pip3', 'install', 'pynvim'],
	      env=env
    )
endpy

Plug 'roxma/nvim-yarp' " required for deoplete
Plug 'roxma/vim-hug-neovim-rpc' " required for deoplete
Plug 'Shougo/deoplete.nvim', {'do': ':UpdateRemotePlugins', 'on': []}
Plug 'ervandew/supertab'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/nerdcommenter'
Plug 'tpope/vim-surround'
Plug 'matze/vim-move' " Move blocks of code with ALT+j/k
Plug 'dense-analysis/ale' " replacement scrooloose/syntastic
Plug 'vim-ruby/vim-ruby'
Plug 'tpope/vim-endwise' " Add 'end' to ruby blocks
Plug 'hashivim/vim-terraform'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rhubarb'
Plug 'gregsexton/gitv', {'on': ['Gitv']}
Plug 'github/copilot.vim'
Plug 'tmux-plugins/vim-tmux-focus-events'
Plug 'tmux-plugins/vim-tmux'
Plug 'fatih/vim-go'
Plug 'thoughtbot/vim-rspec'
Plug 'joukevandermaas/vim-ember-hbs'
Plug 'othree/html5.vim'
Plug 'othree/yajs.vim'
Plug 'othree/es.next.syntax.vim'
Plug 'cakebaker/scss-syntax.vim'

call plug#end()

" Config
" ======
set t_Co=256
set encoding=utf-8
set number
set hidden
set history=100
set nocompatible
set omnifunc=syntaxcomplete#Complete
set ignorecase
set incsearch
set laststatus=2
set backspace=indent,eol,start

try
  set enc=utf-8
  set fileencoding=utf-8
catch
endtry

" clipboard
let g:uname = substitute(system("uname"), '\n\+$', '', '')

if g:uname == 'Linux'
  set clipboard=unnamedplus

  if hostname() == 'ruspa'
    call clipper#set_invocation('nc 10.0.0.2 8377')
  endif
else
  set clipboard=unnamed
endif

" theme
try
  syntax on
  colorscheme monokai
  set background=dark
  let g:airline_powerline_fonts = 1
  set laststatus=2
  let g:airline_theme='powerlineish'
catch
endtry

" Map leader
let mapleader=' '

" Spell
set spelllang=en_gb
set complete+=kspell
nmap <leader>sc :set spell<CR>
nmap <leader>ns :set nospell<CR>

let g:Powerline_symbols = 'fancy'

" Quickly edit/reload the vimrc file

nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

" Map keys
imap jk <ESC>

" Arrows are unvimlike
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>

" splits
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
set splitbelow
set splitright

" File type
autocmd BufRead,BufNewFile {*.markdown,*.mdown,*.mkdn,*.md,*.mkd,*.mdwn,*.mdtxt,*.mdtext,*.text} set filetype=markdown
autocmd BufRead,BufNewFile {Brewfile} set filetype=ruby

" indention
filetype plugin indent on
set nowrap
set tabstop=2
set shiftwidth=2
set softtabstop=2
set smartindent
set autoindent
set expandtab
autocmd Filetype python setlocal ts=4 sw=4 sts=0 expandtab

inoremap <expr><TAB> pumvisible() ? "\<C-n>" : "\<TAB>"

" make supertab close the tern preview
let g:SuperTabClosePreviewOnPopupClose = 1
" make supertab move down instead of up
let g:SuperTabDefaultCompletionType = "<c-n>"

" autoremove white spaces on save
autocmd BufWritePre * :%s/\s\+$//e

" highlight
set hlsearch
set showmatch
nnoremap <silent> <leader>nh :nohl<CR>

" Tabs with Buffers
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ':t'
" To open a new empty buffer
nmap <leader>T :enew<cr>
" Move to the next buffer
nmap <leader>l :bnext<CR>
" Move to the previous buffer
nmap <leader>h :bprevious<CR>
" Close the current buffer and move to the previous one
nmap <leader>q :bp <BAR> bd #<CR>
" Show all open buffers and their status
nmap <leader>bl :ls<CR>

" deoplete.nvim
let g:deoplete#enable_at_startup = 1
" Ale
let g:ale_fixers = {
\   'ruby': ['rubocop'],
\   'javascript': ['prettier', 'eslint'],
\   'css': ['prettier'],
\   'sass': ['stylelint'],
\   'scss': ['stylelint'],
\   'html.handlebars': ['prettier'],
\}

let b:ale_linters = {
\  'ruby': ['rubocop'],
\  'javascript': ['eslint'],
\  'sass': ['sasslint'],
\  'html.handlebars': ['embertemplatelint'],
\}

let g:ale_ruby_rubocop_executable = 'bundle'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_linters_explicit = 1
let g:ale_sign_column_always = 1

" NerdTree
map <C-n> :NERDTreeToggle<CR>
" autocmd FileType nerdtree nmap <buffer> <CR> go

" fzf
map <C-p> :Files<CR>

" Grepper
map <C-g> :Grepper -tool rg<CR>
nmap gs <plug>(GrepperOperator)
xmap gs <plug>(GrepperOperator)

" Golang
let g:go_disable_autoinstall = 0
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1

" Terraform
let g:terraform_fmt_on_save = 1

" Rspec
let g:rspec_command = '!run-rspec {spec}'
map <Leader>sf :call RunCurrentSpecFile()<CR>
map <Leader>sn :call RunNearestSpec()<CR>
map <Leader>sl :call RunLastSpec()<CR>
map <Leader>sa :call RunAllSpecs()<CR>
