# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export EDITOR="vim"
export DISABLE_UPDATE_PROMPT=true

ZSH_THEME="pygmalion"

plugins=(
  git
  vi-mode
  zsh-autosuggestions
  zsh-syntax-highlighting
  zsh-history-substring-search
)

source $ZSH/oh-my-zsh.sh

# VI mode
bindkey -v

# no delay entering normal mode
# https://coderwall.com/p/h63etq
# https://github.com/pda/dotzsh/blob/master/keyboard.zsh#L10
# 10ms for key sequences
KEYTIMEOUT=10

# show vim status
# http://zshwiki.org/home/examples/zlewidgets
function zle-line-init zle-keymap-select {
    RPS1="${${KEYMAP/vicmd/-- NORMAL --}/(main|viins)/-- INSERT --}"
    RPS2=$RPS1

    zle reset-prompt
}

zle -N zle-line-init
zle -N zle-keymap-select

# add missing vim hotkeys
# http://zshwiki.org/home/zle/vi-mode
bindkey -a u undo
bindkey -a '^T' redo
bindkey '^?' backward-delete-char  #backspace

# bind k and j for VI modmd-mode
bindkey -M viins 'jk' vi-cmd-mode
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'l' history-substring-search-down

# bind UP and DOWN arrow keys
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
bindkey "$terminfo[cuu1]" history-substring-search-up
bindkey "$terminfo[cud1]" history-substring-search-down

# path
export PATH=$HOME/.bin:$PATH

# alias
alias sz="source $HOME/.zshrc"
alias zc="$EDITOR $HOME/.zshrc"
alias gPR="simple-pr"
alias gcf="git commit --amend --no-edit"
alias gfu="git add . && git commit --amend --no-edit && git push -f"

function vimgst () {
  g_st=($(git status --porcelain | awk '{print $2}'))
  index="${1:-1}"
  vim $g_st[index]
}

function cbgst () {
  g_st=($(git status --porcelain | awk '{print $2}'))
  index="${1:-1}"
  printf "%s" $g_st[index] | pbcopy
}

# WSL clipboard hack
# https://github.com/Microsoft/WSL/issues/892#issuecomment-275873108
if grep -qE "(Microsoft|WSL)" /proc/version &> /dev/null ; then
  export DISPLAY=localhost:0.0
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
